bodies = [
    "χ1 Ori",
    "χ2 Ori",
    "f1 Ori",
    "ξ Ori",
    "ν Ori",
    "μ Ori",
    "Betelgeuse",
    "Alnitak",
    "Alnilam",
    "Saiph",
    "Rigel",
    "Mintaka",
    "Bellatrix",
    "Meissa",
    "Tabit",
    "Al Taj I",
    "Al Taj IV",
    "Al Taj II",
    "Al Taj II",
    "Al Taj V"
]