bodies = [
    "Mercury",
    "Venus",
    "Moon",
    "Mars",
    "(MI) Phobos",
    "(MII) Deimos",
    "Jupiter",
    "(JI) Io",
    "(JII) Europa",
    "(JIII) Ganymede",
    "(JIV) Callisto",
    "(JV) Amalthea",
    "(JVI) Himalia",
    "(JVII) Elara",
    "(JVIII) Pasiphae",
    "(JIX) Sinope",
    "(JX) Lysithea",
    "(JXI) Carme",
    "(JXII) Ananke",
    "(JXIII) Leda",
    "(JXIV) Thebe",
    "(JXV) Adrastea",
    "(JXVI) Metis",
    "Saturn",
    "(SI) Mimas",
    "(SII) Enceladus",
    "(SIII) Tethys",
    "(SIV) Dione",
    "(SV) Rhea",
    "(SVI) Titan",
    "(SVII) Hyperion",
    "(SVIII) Iapetus",
    "(SIX) Phoebe",
    "(SX) Janus",
    "(SXI) Epimetheus",
    "(SXII) Helene",
    "(SXIII) Telesto",
    "(SXIV) Calypso",
    "(SXV) Atlas",
    "(SXVI) Prometheus",
    "(SXVII) Pandora",
    "(SXVIII) Pan",
    "Uranus",
    "(UI) Ariel",
    "(UII) Umbriel",
    "(UIII) Titania",
    "(UIV) Oberon",
    "(UV) Miranda",
    "(UVI) Cordelia",
    "(UVII) Ophelia",
    "(UIX) Cressida",
    "(UX) Desdemona",
    "(UXI) Juliet",
    "(UXV) Puck",
    "Neptune",
    "(NI) Triton",
    "(NII) Nereid",
    "(NIII) Naiad",
    "(NIV) Thalassa",
    "(NV) Despina",
    "(NVI) Galatea",
    "(NVII) Larissa",
    "(NVIII) Proteus",
    "(NIX) Halimede",
    "(NX) Psamathe",
    "(NXI) Sao",
    "(NXII) Laomedeia",
    "(NXIII) Neso",
    "Pluto",
    "(PI) Charon",
    "(PII) Nix",
    "(PIII) Hydra",
    "(PIV) Kerberos",
    "(PV) Styx"
]