bodies = [
    "Alkaid",
    "Mizar",
    "Alioth",
    "Megrez",
    "Phecda",
    "Taiyangshou",
    "ψ UMa",
    "Tania Australis",
    "Tania Borealis",
    "Merak",
    "Dubhe",
    "Alhaud VII",
    "26 UMa",
    "Alhaud V",
    "Alkaphrah",
    "Talita",
    "Alhaud VI",
    "Muscida",
    "Alhaud IV"
]